### ISSUE TITLE
kw Error

### ISSUE THREAD

**Issue by abhikasera** [VIDILabs/glam#1]
When I'm compiling with c++14 I'm getting this error...
abhikasera@abhikasera:~/Downloads/Project/glam-master/src$ c++ -std=c++14 -I /home/abhikasera/Downloads/Project/glam-master/include main.cpp -o main
main.cpp: In function ‘void compute_shape_delaunay(const Graph&, PositionMap)’:
main.cpp:132:5: error: ‘delaunay_triangulation’ is not a member of ‘kw’
     kw::delaunay_triangulation(s, svp_pos);
     ^
main.cpp: In function ‘void compute_shape_gabriel(const Graph&, PositionMap)’:
main.cpp:147:5: error: ‘delaunay_triangulation’ is not a member of ‘kw’
     kw::delaunay_triangulation(s, svp_pos);

Can you tell me how to run it with Cmake??

**Comment by kwonoh** [comment]
Please see [the Build section of README.md](https://github.com/VIDILabs/glam#build) of this project.

**Comment by abhikasera** [comment]
Where we have to make this directory "bulid"??

**Comment by abhikasera** [comment]
Where we have to make this directory "bulid"??

**Comment by kwonoh** [comment]
The root directory of this project.

**Comment by abhikasera** [comment]
Getting this error....

abhikasera@abhikasera:~/Downloads/Project/glam-master$ cmake .. -DCMAKE_BUILD_TYPE=Release; make
CMake Warning at CMakeLists.txt:9 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.


-- Unable to find TBB
-- Build type: Release
-- USING CXXFLAGS = '-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -frounding-math -O3 -DNDEBUG'
-- USING EXEFLAGS = ' -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed '
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Requested component: Core
-- Requested component: MPFR
-- Requested component: GMP
CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.62 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:28 (find_package)


CMake Error at CMakeLists.txt:35 (message):
  Unable to find boost


-- Configuring incomplete, errors occurred!
See also "/home/abhikasera/Downloads/Project/glam-master/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.

**Comment by kwonoh** [comment]
Unfortunately, I don’t have time for answer your questions that are not the issue of this project. Please install all the required libraries with correct version. Also, google the error messages yourself.

**Comment by abhikasera** [comment]
Can you help me from initial that where to install all the library files like boost, CGAL etc.

**Comment by abhikasera** [comment]
I have installed all the library in the include folder of the project. Is it okay?

**Comment by kwonoh** [comment]
Again, you are asking basic software package management questions. Insatalling a software library depends on your operating system and software package manager. Please google yourself how to install the required libraries based on your environment.
