### ISSUE TITLE
How Can I install it?

### ISSUE THREAD

**Issue by khaled-rahman** [VIDILabs/glam#2]
I am facing the following problems while installing it. What might be the reason?

/data/morahma/Softwars/glam/include/kw/algorithm/normalize.hpp:32:41: error: parameter declared ‘auto’
     tbb::parallel_for_each(c, [=](auto& x) { x = (x - min) / range; });
                                         ^
/data/morahma/Softwars/glam/include/kw/algorithm/normalize.hpp: In lambda function:
/data/morahma/Softwars/glam/include/kw/algorithm/normalize.hpp:32:46: error: ‘x’ was not declared in this scope
     tbb::parallel_for_each(c, [=](auto& x) { x = (x - min) / range; });
                                              ^
In file included from /data/morahma/Softwars/glam/include/kw/graph/layout/metric.hpp:10:0,
                 from /data/morahma/Softwars/glam/src/main.cpp:14:
/data/morahma/Softwars/glam/include/kw/graph/layout/metric/edge_length.hpp: In function ‘double kw::edge_length_cv(const Graph&, PositionMap)’:
/data/morahma/Softwars/glam/include/kw/graph/layout/metric/edge_length.hpp:39:18: error: parameter declared ‘auto’
         [&](auto itr) {
                  ^
/data/morahma/Softwars/glam/include/kw/graph/layout/metric/edge_length.hpp: In lambda function:
/data/morahma/Softwars/glam/include/kw/graph/layout/metric/edge_length.hpp:40:42: error: ‘itr’ was not declared in this scope
             auto const e = boost::get<0>(itr);
                                          ^
In file included from /data/morahma/Softwars/glam/include/kw/graph/layout/metric.hpp:11:0,
                 from /data/morahma/Softwars/glam/src/main.cpp:14:
/data/morahma/Softwars/glam/include/kw/graph/layout/metric/min_angle.hpp: In function ‘double kw::min_angle_metric(const Graph&, PositionMap)’:
/data/morahma/Softwars/glam/include/kw/graph/layout/metric/min_angle.hpp:48:69: error: parameter declared ‘auto’
         kw::make_iterator_range(boost::vertices(g)), [&](auto const u) {
                                                                     ^

**Comment by kwonoh** [comment]
Have you installed all the required packages in [`README.md`](https://github.com/VIDILabs/glam/blob/master/README.md)?

**Comment by khaled-rahman** [comment]
Hi,
Thank you. I installed it.
